# 认证失败时返回自定义信息

## 认证失败时抛出异常的流程

1. UserDetailsService 抛出异常

```java
public class MyUserDetailsService implements UserDetailsService {
    @Override
    public UserDetails loadUserByUsername(String name) throws UsernameNotFoundException {
        // ...
        MyUser user = feign.getUserByUsername(loginVo);
        if (response == null) {
            throw new UsernameNotFoundException("用户名、密码或验证码错误!");
        }
        // ...
    }
}
```

2. 进入 AbstractAuthenticationProcessingFilter 的 doFilter 方法
```java
private void doFilter(HttpServletRequest request, HttpServletResponse response, FilterChain chain) throws IOException, ServletException {
    if (!this.requiresAuthentication(request, response)) {
        chain.doFilter(request, response);
    } else {
        try {
            Authentication authenticationResult = this.attemptAuthentication(request, response);
            if (authenticationResult == null) {
                return;
            }

            this.sessionStrategy.onAuthentication(authenticationResult, request, response);
            if (this.continueChainBeforeSuccessfulAuthentication) {
                chain.doFilter(request, response);
            }

            this.successfulAuthentication(request, response, chain, authenticationResult);
        } catch (InternalAuthenticationServiceException var5) {
            this.logger.error("An internal error occurred while trying to authenticate the user.", var5);
            this.unsuccessfulAuthentication(request, response, var5);
        } catch (AuthenticationException var6) {
            this.unsuccessfulAuthentication(request, response, var6);
        }

    }
}
```

3. 进入 AbstractUserDetailsAuthenticationProvider 的 authenticate 进行认证处理

```java
public abstract class AbstractUserDetailsAuthenticationProvider implements AuthenticationProvider, InitializingBean, MessageSourceAware {
    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
        // ...
        UserDetails user = this.userCache.getUserFromCache(username);
        if (user == null) {
            cacheWasUsed = false;

            try {
                user = this.retrieveUser(username, (UsernamePasswordAuthenticationToken)authentication);
            } catch (UsernameNotFoundException var6) {
                this.logger.debug("Failed to find user '" + username + "'");
                if (!this.hideUserNotFoundExceptions) {
                    throw var6;
                }

                throw new BadCredentialsException(this.messages.getMessage("AbstractUserDetailsAuthenticationProvider.badCredentials", "Bad credentials"));
            }

            // ...
        }

        // ...
}
```

4. **捕获到 UsernameNotFoundException 的异常，并封装 BadCredentialsException ，异常信息默认为 "Bad credentials"**

5. 抛出的 BadCredentialsException 异常由 AbstractAuthenticationProcessingFilter 的 doFilter 捕获，并交给 unsuccessfulAuthentication 处理

```java
protected void unsuccessfulAuthentication(HttpServletRequest request, HttpServletResponse response, AuthenticationException failed) throws IOException, ServletException {
    // ...
    this.failureHandler.onAuthenticationFailure(request, response, failed);
}
```

6. 进入 SimpleUrlAuthenticationFailureHandler 的 onAuthenticationFailure

```java
public void onAuthenticationFailure(HttpServletRequest request, HttpServletResponse response, AuthenticationException exception) throws IOException, ServletException {
    // ...
        this.saveException(request, exception);
    // ...
}
```

7. 将流程交给 saveException 处理

```java
protected final void saveException(HttpServletRequest request, AuthenticationException exception) {
    if (this.forwardToDestination) {
        request.setAttribute("SPRING_SECURITY_LAST_EXCEPTION", exception);
    } else {
        HttpSession session = request.getSession(false);
        if (session != null || this.allowSessionCreation) {
            request.getSession().setAttribute("SPRING_SECURITY_LAST_EXCEPTION", exception);
        }

    }
}
```

8. 最后，异常信息被保存在 **```session[SPRING_SECURITY_LAST_EXCEPTION]```**

## 后台抛出自定义异常

```java
public class MyUserDetailsService implements UserDetailsService {
    @Override
    public UserDetails loadUserByUsername(String name) throws UsernameNotFoundException {
        // ...
        MyUser user = feign.getUserByUsername(loginVo);
        if (user == null) {
            // 注意：
            // 虽然接口方法抛出的是 UsernameNotFoundException
            // 但是为了避免 oauth2 返回统一的异常信息 "Bad credentials"，此处需抛出 BadCredentialsException （原因参考上述的源码分析流程）
            // 这样，前端才能获取到实际的业务异常信息，否则前端就只能获取到固定的异常信息 "Bad credentials"
            throw new BadCredentialsException("用户名、密码或验证码错误!");
        }
        // ...
    }
}
```

## 前端显示异常信息

```html
<p id="error" th:if="${param.error}" th:text="${session['SPRING_SECURITY_LAST_EXCEPTION'].message}"></p>
```
